---
output:
  md_document:
    variant: markdown_github
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.path = "README-",
  message = FALSE,
  warning = FALSE
)
```

# allinone

> All-in-on model based custom predictions

Install

```{r eval=FALSE}
remotes::install_github("ABbiodiversity/allinone")
```

Load the package, then download and load the coefs, etc.

```{r}
library(allinone)

#ai_dowload_coefs()

ai_load_coefs()

tab <- ai_species()
str(tab)

## example data to see what is needed and how it is formatted
load(system.file("extdata/example.RData", package="allinone"))

## define species and bootstrap id
spp <- "AlderFlycatcher"
i <- 1
# 1:2880, 1:231

## use composition
z1 <- ai_predict(spp, 
  spclim=spclim, 
  veghf=p_veghf, 
  soilhf=p_soilhf,
  i=i)
str(z1)

## sector effects
library(mefa4)
lt <- ai_classes()
ltn <- nonDuplicated(lt$north, Label, TRUE)
lts <- nonDuplicated(lt$south, Label, TRUE)

Nn <- groupSums(z1$north, 2, ltn[colnames(z1$north), "Sector"])
Ns <- groupSums(z1$south, 2, lts[colnames(z1$south), "Sector"])
Ns <- cbind(Ns, Forestry=0)
N <- spclim$wN * Nn + (1-spclim$wN) * Ns
colSums(Nn)
colSums(Ns)
colSums(N)


## use land cover classes
z2 <- ai_predict(spp, 
  spclim=spclim, 
  veghf=spclim$veghf, 
  soilhf=spclim$soilhf,
  i=i)
str(z2)

## averaging predictions
avg2 <- spclim$wN * rowSums(z2$north) + (1-spclim$wN) * rowSums(z2$south)
str(avg2)
```

